spring.application.name=challenge

# data source (MySQL) - .env 에서 주입
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# session persistence
server.servlet.session.persistent=false

# jpa
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# logging
logging.level.root=info
logging.level.com.mycom.myapp=DEBUG

# jwt secret key - .env 에서 주입
myapp.jwt.secret=${JWT_SECRET}
# jwt 유효기간(ms) - access 24시간, refresh 14일
myapp.jwt.access-exp=86400000
myapp.jwt.refresh-exp=1209600000
